### ISSUE TITLE
bug: TS2339 Property 'x' does not exist on type 'Y' caught and stops migration

### ISSUE THREAD

**Issue by wondersloth** [rehearsal-js/rehearsal-js#1070]
Internal Issue working on fixing:
`lib/core/addon/services/linkedin-urls.ts` in `learning-web`

```
$ yarn rehearsal fix --no-graph lib/core/addon/services/linkedin-urls.ts
info:    @rehearsal/fix 3.0.4-beta
✔ Initialize
✖ Debug Failure. False expression: Token end is child end
```

## Test Case

```
import { External } from 'some-package'; // This package has an unknown implementation. No Types.

class Something extends External {
  constructor(...args) {
    super(...args)
    this.setRoutes({
      'enterprise-cookies': "",
      'feed.update': "",
      'help.ads': "",
      'help.binding-benefits': "",
      'help.certificates': "",
      'help.disability-answer-desk': "",
      'help.instructor-analytics': "",
      'help.learning': "",
      'help.learning-privacy': "",
      'help.learning-progress': "",
      'help.learning-teams': "",
      'help.china': "",
      'help.likes': "",
      'help.lms-completion': "",
      'help.lynda-subscriber': "",
      'help.questions-privacy': "",
      'help.reviews': "",
      'help.share-certificate': "",
      'help.sync-learning-history': "",
    });
  }
}
```

## Context

The problem I can deduce with the source file is that it's attempting to call `this.setRoutes()` but it doesn't have that method.

This breaks the internals in rehearsal can throws:

```
Debug Failure. False expression: Token end is child end
```

Running the debugger and iterating over the diagnostics:

We see:

```
"Property 'setRoutes' does not exist on type 'LearningLinkedinUrlsService'."
```

https://github.com/rehearsal-js/rehearsal-js/blame/e06327da9a1f784bbcbda1f9d581ae4ef3652472/packages/codefixes/src/typescript-codefix-collection.ts#L50

### Stack Trace
```
Uncaught Error Error: Debug Failure. False expression: Token end is child end
    at fail (/node_modules/typescript/lib/typescript.js:1811:19)
    at assert (/node_modules/typescript/lib/typescript.js:1830:13)
    at processChildNode (/node_modules/typescript/lib/typescript.js:166208:19)
    at <anonymous> (/node_modules/typescript/lib/typescript.js:166139:11)
    at visitNode2 (/node_modules/typescript/lib/typescript.js:27583:20)
    at forEachChildInPropertySignature (/node_modules/typescript/lib/typescript.js:28046:65)
    at forEachChild (/node_modules/typescript/lib/typescript.js:27676:37)
    at processNode (/node_modules/typescript/lib/typescript.js:166136:7)
    at processChildNode (/node_modules/typescript/lib/typescript.js:166215:9)
    at processChildNodes (/node_modules/typescript/lib/typescript.js:166258:34)
    at <anonymous> (/node_modules/typescript/lib/typescript.js:166152:11)
    at visitNodes (/node_modules/typescript/lib/typescript.js:27588:16)
    at forEachChildInTypeLiteral (/node_modules/typescript/lib/typescript.js:28105:18)
    at forEachChild (/node_modules/typescript/lib/typescript.js:27676:37)
    at processNode (/node_modules/typescript/lib/typescript.js:166136:7)
    at processChildNode (/node_modules/typescript/lib/typescript.js:166215:9)
    at <anonymous> (/node_modules/typescript/lib/typescript.js:166139:11)
    at visitNode2 (/node_modules/typescript/lib/typescript.js:27583:20)
    at forEachChildInParameter (/node_modules/typescript/lib/typescript.js:28040:183)
    at forEachChild (/node_modules/typescript/lib/typescript.js:27676:37)
    at processNode (/node_modules/typescript/lib/typescript.js:166136:7)
    at processChildNode (/node_modules/typescript/lib/typescript.js:166215:9)
    at processChildNodes (/node_modules/typescript/lib/typescript.js:166258:34)
    at <anonymous> (/node_modules/typescript/lib/typescript.js:166152:11)
    at visitNodes (/node_modules/typescript/lib/typescript.js:27588:16)
    at forEachChildInMethodDeclaration (/node_modules/typescript/lib/typescript.js:28069:279)
    at forEachChild (/node_modules/typescript/lib/typescript.js:27676:37)
    at processNode (/node_modules/typescript/lib/typescript.js:166136:7)
    at formatSpanWorker (/node_modules/typescript/lib/typescript.js:165944:7)
    at <anonymous> (/node_modules/typescript/lib/typescript.js:165884:107)
    at getFormattingScanner (/node_modules/typescript/lib/typescript.js:164659:17)
    at formatNodeGivenIndentation (/node_modules/typescript/lib/typescript.js:165884:12)
    at getFormattedTextOfNode (/node_modules/typescript/lib/typescript.js:164392:49)
    at format (/node_modules/typescript/lib/typescript.js:164372:33)
    at computeNewText (/node_modules/typescript/lib/typescript.js:164373:225)
    at <anonymous> (/node_modules/typescript/lib/typescript.js:164334:31)
    at mapDefined (/node_modules/typescript/lib/typescript.js:374:24)
    at <anonymous> (/node_modules/typescript/lib/typescript.js:164332:34)
    at mapDefined (/node_modules/typescript/lib/typescript.js:374:24)
    at getTextChangesFromChanges (/node_modules/typescript/lib/typescript.js:164326:18)
    at getChanges (/node_modules/typescript/lib/typescript.js:164314:41)
    at with (/node_modules/typescript/lib/typescript.js:163812:26)
    at addMethodDeclarationChanges (/node_modules/typescript/lib/typescript.js:142592:102)
    at getActionsForMissingMethodDeclaration (/node_modules/typescript/lib/typescript.js:142593:61)
    at getCodeActions (/node_modules/typescript/lib/typescript.js:142913:30)
    at <anonymous> (/node_modules/typescript/lib/typescript.js:137216:48)
    at flatMap (/node_modules/typescript/lib/typescript.js:303:19)
    at getFixes (/node_modules/typescript/lib/typescript.js:137216:12)
    at <anonymous> (/node_modules/typescript/lib/typescript.js:133697:35)
    at flatMap (/node_modules/typescript/lib/typescript.js:303:19)
    at getCodeFixesAtPosition (/node_modules/typescript/lib/typescript.js:133695:14)
    at getFixesForDiagnostic (/node_modules/@rehearsal/codefixes/dist/src/typescript-codefix-collection.js:30:37)
    at getCodeFixes (/node_modules/@rehearsal/codefixes/dist/src/codefixes-provider.js:14:56)
    at getCodeFix (/node_modules/@rehearsal/plugins/dist/src/plugins/diagnostic-fix.plugin.js:121:33)
```

## Why is breaking in learning-web?
They have an upstream library **learning-web-common** that a class extends. This package doesn't have any types.

## Recommendation
In general, we need to not stop migration if we fail to `getCodeFixesAtPosition()`

Maybe add a comment, unable to apply code fixes at this position.

**Comment by wondersloth** [comment]
TS Issue https://github.com/microsoft/TypeScript/issues/54366
