### ISSUE TITLE
bug(graph):  parsing failure when when encountering jsx syntax in a .js file

### ISSUE THREAD

**Issue by wondersloth** [rehearsal-js/rehearsal-js#1244]
A common internal use case is having a `docusaurus` directory for documentation where there are `.js` files that will contain embedded `jsx`  templates in the `.js` file.

`es-module-lexer` will throw an error if it cannot parse the file:
```
$ yarn rehearsal graph ./docusaurus/src/pages/tokens.js
yarn run v1.22.15
/node_modules/.bin/rehearsal graph ./docusaurus/src/pages/tokens.js
✖ Parse error @:17:22

node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^
Error: Parse error @:17:22
    at parse (file:///Users/medwards/Code/hue-web-foundations/node_modules/@rehearsal/migration-graph/node_modules/es-module-lexer/dist/lexer.js:2:358)
    at Resolver.walk (file:///Users/medwards/Code/hue-web-foundations/node_modules/@rehearsal/migration-graph/dist/src/resolver.js:65:27)
    at file:///Users/medwards/Code/hue-web-foundations/node_modules/@rehearsal/cli/dist/src/commands/graph/tasks/graphWorker.js:19:18 {
  idx: 550
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### How do we address this?

- **Short** term ignore migrating `docusaurus` directories for now.
- **Medium** Try/catch around the parse method in https://github.com/rehearsal-js/rehearsal-js/blob/58f39eb2e6944202c7f52dccbb9e9487d834b65a/packages/migration-graph/src/resolver.ts#L103
  - In the graph meta (if possible) report that this node was not walkable and skip it. 
  - This should be reported in the cli and graphviz output that it was not walkable.
- **Long** Add support for parsing **.js** iles with **.jsx** embedded. Unsure of the the use case in react development to have it embedded in `.js` and not `.jsx`

**Comment by wondersloth** [comment]
#1245 solves the original bug
