### ISSUE TITLE
After rehearsal migrate; Error when running yarn eslint on project; Malformed .eslitnrc.js

### ISSUE THREAD

**Issue by wondersloth** [rehearsal-js/rehearsal-js#678]
### Steps to Reproduce
Checkout `urn-utils`,
Following the steps in our internal guide for early adopter usage:

After you run:
```
$ rehearsal migrate -u rehearsal-config.json
```

Now try and lint your src files:

```
$ yarn eslint
```
OR, specifically in `urn-utils`
```
$ yarn test
```

eslint will fail will have the following error:

```
➜  urn-utils git:(master) ✗ yarn test

Oops! Something went wrong! :(

ESLint: 8.32.0

Error: ESLint configuration in .eslintrc.js is invalid:
        - Unexpected top-level property "plugin".

    at ConfigValidator.validateConfigSchema (/Users/medwards/Code/urn-utils/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2156:19)
    at ConfigArrayFactory._normalizeConfigData (/Users/medwards/Code/urn-utils/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2998:19)
    at ConfigArrayFactory.loadInDirectory (/Users/medwards/Code/urn-utils/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2866:33)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/medwards/Code/urn-utils/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3848:46)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/medwards/Code/urn-utils/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3867:20)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/Users/medwards/Code/urn-utils/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3769:18)
    at FileEnumerator._iterateFilesRecursive (/Users/medwards/Code/urn-utils/node_modules/eslint/lib/cli-engine/file-enumerator.js:448:49)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator.iterateFiles (/Users/medwards/Code/urn-utils/node_modules/eslint/lib/cli-engine/file-enumerator.js:299:49)
    at iterateFiles.next (<anonymous>)
```

### Suggested fix
Rename value in `.eslintrc.js` from `plugin` to `plugins`

**Comment by wondersloth** [comment]
@brendaHuang fixed this issue with our internal generated rehearsal-cli-config repo. This is not an issue with rehearsal-js.
