### ISSUE TITLE
BUG: `@rehearsa/cli` `dependency-install.js` should not fail if a dependency already exists

### ISSUE THREAD

**Issue by wondersloth** [rehearsal-js/rehearsal-js#919]
## Summary
If a target project has `prettier` the install of dependencies fails.

### Error

The error is being swallowed.

```
› Installing devDependencies: @types/node, @typescript-eslint/eslint-plugin, @typescript-eslint/parser, eslint, eslint-config-prettier, eslint-plugin-prettier, prettier, ty…
Error: Command failed with exit code 126: volta run yarn add -D @types/node @typescript-eslint/eslint-plugin @typescript-eslint/parser eslint eslint-config-prettier eslint-plugin-prettier prettier typescript @linkedin/ts-bases @linkedin/eslint-plugin-typescript @typescript-eslint/eslint-plugin@>= 5.0.0 @typescript-eslint/parser@>= 5.0.0 eslint@>= 7.0.0 eslint-import-resolver-typescript@>= 2.5.0 eslint-plugin-filenames@>= 1.3.2 eslint-plugin-import@>= 2.25.2 eslint-plugin-node@>= 11.1.0 eslint-plugin-simple-import-sort@>= 7.0.0 eslint-plugin-tsdoc@>= 0.2.14 eslint-plugin-unicorn@>= 39.0.0 @glint/core @glint/template @glint/environment-ember-loose ember-template-imports @glint/environment-ember-template-imports
Usage Error: Package "prettier" is already listed as a regular dependency - remove the -D,-P flags or remove it from your dependencies first

$ yarn add [--json] [-E,--exact] [-T,--tilde] [-C,--caret] [-D,--dev] [-P,--peer] [-O,--optional] [--prefer-dev] [-i,--interactive] [--cached] [--mode #0] ...
    at makeError (file:///Users/medwards/.volta/tools/image/packages/@rehearsal/cli/lib/node_modules/@rehearsal/cli/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///Users/medwards/.volta/tools/image/packages/@rehearsal/cli/lib/node_modules/@rehearsal/cli/node_modules/execa/index.js:124:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async addDep (file:///Users/medwards/.volta/tools/image/packages/@rehearsal/cli/lib/node_modules/@rehearsal/cli/node_modules/@rehearsal/utils/dist/src/cli.js:269:5)
    at async Task.task (file:///Users/medwards/.volta/tools/image/packages/@rehearsal/cli/lib/node_modules/@rehearsal/cli/dist/src/commands/migrate/tasks/dependency-install.js:92:21)
    at async Task.run (file:///Users/medwards/.volta/tools/image/packages/@rehearsal/cli/lib/node_modules/@rehearsal/cli/node_modules/listr2/dist/index.js:935:11)
    at async /Users/medwards/.volta/tools/image/packages/@rehearsal/cli/lib/node_modules/@rehearsal/cli/node_modules/p-map/index.js:57:22 {
  shortMessage: 'Command failed with exit code 126: volta run yarn add -D @types/node @typescript-eslint/eslint-plugin @typescript-eslint/parser eslint eslint-config-prettier eslint-plugin-prettier prettier typescript @linkedin/ts-bases @linkedin/eslint-plugin-typescript @typescript-eslint/eslint-plugin@>= 5.0.0 @typescript-eslint/parser@>= 5.0.0 eslint@>= 7.0.0 eslint-import-resolver-typescript@>= 2.5.0 eslint-plugin-filenames@>= 1.3.2 eslint-plugin-import@>= 2.25.2 eslint-plugin-node@>= 11.1.0 eslint-plugin-simple-import-sort@>= 7.0.0 eslint-plugin-tsdoc@>= 0.2.14 eslint-plugin-unicorn@>= 39.0.0 @glint/core @glint/template @glint/environment-ember-loose ember-template-imports @glint/environment-ember-template-imports',
  command: 'volta run yarn add -D @types/node @typescript-eslint/eslint-plugin @typescript-eslint/parser eslint eslint-config-prettier eslint-plugin-prettier prettier typescript @linkedin/ts-bases @linkedin/eslint-plugin-typescript @typescript-eslint/eslint-plugin@>= 5.0.0 @typescript-eslint/parser@>= 5.0.0 eslint@>= 7.0.0 eslint-import-resolver-typescript@>= 2.5.0 eslint-plugin-filenames@>= 1.3.2 eslint-plugin-import@>= 2.25.2 eslint-plugin-node@>= 11.1.0 eslint-plugin-simple-import-sort@>= 7.0.0 eslint-plugin-tsdoc@>= 0.2.14 eslint-plugin-unicorn@>= 39.0.0 @glint/core @glint/template @glint/environment-ember-loose ember-template-imports @glint/environment-ember-template-imports',
  escapedCommand: 'volta run yarn add -D "@types/node" "@typescript-eslint/eslint-plugin" "@typescript-eslint/parser" eslint eslint-config-prettier eslint-plugin-prettier prettier typescript "@linkedin/ts-bases" "@linkedin/eslint-plugin-typescript" "@typescript-eslint/eslint-plugin@>= 5.0.0" "@typescript-eslint/parser@>= 5.0.0" "eslint@>= 7.0.0" "eslint-import-resolver-typescript@>= 2.5.0" "eslint-plugin-filenames@>= 1.3.2" "eslint-plugin-import@>= 2.25.2" "eslint-plugin-node@>= 11.1.0" "eslint-plugin-simple-import-sort@>= 7.0.0" "eslint-plugin-tsdoc@>= 0.2.14" "eslint-plugin-unicorn@>= 39.0.0" "@glint/core" "@glint/template" "@glint/environment-ember-loose" ember-template-imports "@glint/environment-ember-template-imports"',
  exitCode: 126,
```

```
✖ We ran into an error when installing devDependencies, please install the following as devDependencies and try again.
  - @types/node
  - @typescript-eslint/eslint-plugin
  - @typescript-eslint/parser
  - eslint
  - eslint-config-prettier
  - eslint-plugin-prettier
  - prettier
  - typescript
  - @linkedin/ts-bases
  - @linkedin/eslint-plugin-typescript
  - @typescript-eslint/eslint-plugin@>= 5.0.0
  - @typescript-eslint/parser@>= 5.0.0
  - eslint@>= 7.0.0
  - eslint-import-resolver-typescript@>= 2.5.0
  - eslint-plugin-filenames@>= 1.3.2
  - eslint-plugin-import@>= 2.25.2
  - eslint-plugin-node@>= 11.1.0
  - eslint-plugin-simple-import-sort@>= 7.0.0
  - eslint-plugin-tsdoc@>= 0.2.14
  - eslint-plugin-unicorn@>= 39.0.0
  - @glint/core
  - @glint/template
  - @glint/environment-ember-loose
◼ Create tsconfig.json
◼ Create eslint config
◼ Add package scripts
error:   We ran into an error when installing devDependencies, please install the following as devDependencies and try again.
  - @types/node
  - @typescript-eslint/eslint-plugin
  - @typescript-eslint/parser
  - eslint
  - eslint-config-prettier
  - eslint-plugin-prettier
  - prettier
  - typescript
  - @linkedin/ts-bases
  - @linkedin/eslint-plugin-typescript
  - @typescript-eslint/eslint-plugin@>= 5.0.0
  - @typescript-eslint/parser@>= 5.0.0
  - eslint@>= 7.0.0
  - eslint-import-resolver-typescript@>= 2.5.0
  - eslint-plugin-filenames@>= 1.3.2
  - eslint-plugin-import@>= 2.25.2
  - eslint-plugin-node@>= 11.1.0
  - eslint-plugin-simple-import-sort@>= 7.0.0
  - eslint-plugin-tsdoc@>= 0.2.14
  - eslint-plugin-unicorn@>= 39.0.0
  - @glint/core
  - @glint/template
  - @glint/environment-ember-loose
Error: We ran into an error when installing devDependencies, please install the following as devDependencies and try again.
  - @types/node
  - @typescript-eslint/eslint-plugin
  - @typescript-eslint/parser
  - eslint
  - eslint-config-prettier
  - eslint-plugin-prettier
  - prettier
  - typescript
  - @linkedin/ts-bases
  - @linkedin/eslint-plugin-typescript
  - @typescript-eslint/eslint-plugin@>= 5.0.0
  - @typescript-eslint/parser@>= 5.0.0
  - eslint@>= 7.0.0
  - eslint-import-resolver-typescript@>= 2.5.0
  - eslint-plugin-filenames@>= 1.3.2
  - eslint-plugin-import@>= 2.25.2
  - eslint-plugin-node@>= 11.1.0
  - eslint-plugin-simple-import-sort@>= 7.0.0
  - eslint-plugin-tsdoc@>= 0.2.14
  - eslint-plugin-unicorn@>= 39.0.0
  - @glint/core
  - @glint/template
  - @glint/environment-ember-loose
    at Task.task (file:///Users/medwards/.volta/tools/image/packages/@rehearsal/cli/lib/node_modules/@rehearsal/cli/dist/src/commands/migrate/tasks/dependency-install.js:98:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Task.run (file:///Users/medwards/.volta/tools/image/packages/@rehearsal/cli/lib/node_modules/@rehearsal/cli/node_modules/listr2/dist/index.js:935:11)
    at async /Users/medwards/.volta/tools/image/packages/@rehearsal/cli/lib/node_modules/@rehearsal/cli/node_modules/p-map/index.js:57:22
```

## Steps to reproduce
- `$ ... clone learning-web`
- `$ rehearsal-cli-conig migrate-config init --ci`
- `$ rehearsal migrate init --ci`
- See failure
- `$ yarn remove prettier`
- `$ rehearsal migrate init`

**Comment by lynchbomb** [comment]
Yeah this is happening because we "downgrading" the dependency from dep to devDep

**Comment by lynchbomb** [comment]
that' error is not coming from rehearsal

**Comment by brendaHuang-2023** [comment]
Another case of this bug is for `ember-template-imports`. Running into this error when migrating against ember-cli-pemberly-i18n.
