### ISSUE TITLE
Bug: failed dependency install or other thrown error doesn't result in process.exit code > 0

### ISSUE THREAD

**Issue by wondersloth** [rehearsal-js/rehearsal-js#924]
## Steps to reproduce

- Check out hue-web-button or any MP.
- Put a typo package name in the `rehearsal-config.json`
- `$ rehearsal migrate --ci --verbose`
- This should fail and error.
- Run `$ echo $?` to see the process exit value for the last command. It will return `0`.

## Output from failure
```
➜  hue-web-button git:(master) ✗ rehearsal migrate --ci --verbose
info:    @rehearsal/migrate 1.0.16-beta
warn:    You have uncommitted files in your repo. You might want to commit or stash them.
✔ Validate project
✔ Initialize
✖ We ran into an error when installing devDependencies, please install the following as devDependencies and try again.
  - @types/node
  - @typescript-eslint/eslint-plugin
  - @typescript-eslint/parser
  - eslint
  - eslint-config-prettier
  - eslint-plugin-prettier
  - prettier
  - typescript
  - @linkedin/ts-bases
  - @linkedin/eslint-plugin-typescript
  - @typescript-eslint/eslint-plugin@>= 5.0.0
  - @typescript-eslint/parser@>= 5.0.0
  - eslint@>= 7.0.0
  - eslint-import-resolver-typescript@>= 2.5.0
  - eslint-plugin-filenames@>= 1.3.2
  - eslint-plugin-import@>= 2.25.2
  - eslint-plugin-node@>= 11.1.0
  - eslint-plugin-simple-import-sort@>= 7.0.0
  - eslint-plugin-tsdoc@>= 0.2.14
  - eslint-plugin-unicorn@>= 39.0.0
  - @glint/core
  - @glint/templatee
  - @glint/environment-ember-loose
◼ Create tsconfig.json
◼ Create eslint config
◼ Add package scripts
◼ Analyzing Project
◼ Convert JS files to TS
error:   We ran into an error when installing devDependencies, please install the following as devDependencies and try again.
  - @types/node
  - @typescript-eslint/eslint-plugin
  - @typescript-eslint/parser
  - eslint
  - eslint-config-prettier
  - eslint-plugin-prettier
  - prettier
  - typescript
  - @linkedin/ts-bases
  - @linkedin/eslint-plugin-typescript
  - @typescript-eslint/eslint-plugin@>= 5.0.0
  - @typescript-eslint/parser@>= 5.0.0
  - eslint@>= 7.0.0
  - eslint-import-resolver-typescript@>= 2.5.0
  - eslint-plugin-filenames@>= 1.3.2
  - eslint-plugin-import@>= 2.25.2
  - eslint-plugin-node@>= 11.1.0
  - eslint-plugin-simple-import-sort@>= 7.0.0
  - eslint-plugin-tsdoc@>= 0.2.14
  - eslint-plugin-unicorn@>= 39.0.0
  - @glint/core
  - @glint/templatee
  - @glint/environment-ember-loose
Error: We ran into an error when installing devDependencies, please install the following as devDependencies and try again.
  - @types/node
  - @typescript-eslint/eslint-plugin
  - @typescript-eslint/parser
  - eslint
  - eslint-config-prettier
  - eslint-plugin-prettier
  - prettier
  - typescript
  - @linkedin/ts-bases
  - @linkedin/eslint-plugin-typescript
  - @typescript-eslint/eslint-plugin@>= 5.0.0
  - @typescript-eslint/parser@>= 5.0.0
  - eslint@>= 7.0.0
  - eslint-import-resolver-typescript@>= 2.5.0
  - eslint-plugin-filenames@>= 1.3.2
  - eslint-plugin-import@>= 2.25.2
  - eslint-plugin-node@>= 11.1.0
  - eslint-plugin-simple-import-sort@>= 7.0.0
  - eslint-plugin-tsdoc@>= 0.2.14
  - eslint-plugin-unicorn@>= 39.0.0
  - @glint/core
  - @glint/templatee
  - @glint/environment-ember-loose
    at Task.task (file:///Users/medwards/.volta/tools/image/packages/@rehearsal/cli/lib/node_modules/@rehearsal/cli/dist/src/commands/migrate/tasks/dependency-install.js:98:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Task.run (file:///Users/medwards/.volta/tools/image/packages/@rehearsal/cli/lib/node_modules/@rehearsal/cli/node_modules/listr2/dist/index.js:935:11)
    at async /Users/medwards/.volta/tools/image/packages/@rehearsal/cli/lib/node_modules/@rehearsal/cli/node_modules/p-map/index.js:57:22
➜  hue-web-button git:(master) ✗ echo $?                           
0
```

**Comment by lynchbomb** [comment]
This is because the try/catch around depInstall step isn’t including the actual error into listr

**Comment by egorio** [comment]
Close due to removing dependency installation step from rehearsal
