### ISSUE TITLE
Bug: migrate fails on node-tests because of prettier

### ISSUE THREAD

**Issue by brendaHuang-2023** [rehearsal-js/rehearsal-js#933]
Migrate fails on gts files because of prettier: 

```
✖ No parser could be inferred for file: /Users/brehuang/dev/ember-cli-pemberly-i18n/node-tests/fixtures/ast-re…
  Occurred while linting /Users/brehuang/dev/ember-cli-pemberly-i18n/node-tests/fixtures/ast-rewriter-test/sam…
  Rule: "prettier/prettier"
error:   No parser could be inferred for file: /Users/brehuang/dev/ember-cli-pemberly-i18n/node-tests/fixtures/ast-rewriter-test/sample1.gts/0_/Users/brehuang/dev/ember-cli-pemberly-i18n/node-tests/fixtures/ast-rewriter-test/sample1.gts/0_/Users/brehuang/dev/ember-cli-pemberly-i18n/node-tests/fixtures/ast-rewriter-test/sample1.gts/0_/Users/brehuang/dev/ember-cli-pemberly-i18n/node-tests/fixtures/ast-rewriter-test/sample1.gts
Occurred while linting /Users/brehuang/dev/ember-cli-pemberly-i18n/node-tests/fixtures/ast-rewriter-test/sample1.gts/0_/Users/brehuang/dev/ember-cli-pemberly-i18n/node-tests/fixtures/ast-rewriter-test/sample1.gts/0_/Users/brehuang/dev/ember-cli-pemberly-i18n/node-tests/fixtures/ast-rewriter-test/sample1.gts/0_/Users/brehuang/dev/ember-cli-pemberly-i18n/node-tests/fixtures/ast-rewriter-test/sample1.gts:1
Rule: "prettier/prettier"
Error: No parser could be inferred for file: /Users/brehuang/dev/ember-cli-pemberly-i18n/node-tests/fixtures/ast-rewriter-test/sample1.gts/0_/Users/brehuang/dev/ember-cli-pemberly-i18n/node-tests/fixtures/ast-rewriter-test/sample1.gts/0_/Users/brehuang/dev/ember-cli-pemberly-i18n/node-tests/fixtures/ast-rewriter-test/sample1.gts/0_/Users/brehuang/dev/ember-cli-pemberly-i18n/node-tests/fixtures/ast-rewriter-test/sample1.gts
Occurred while linting /Users/brehuang/dev/ember-cli-pemberly-i18n/node-tests/fixtures/ast-rewriter-test/sample1.gts/0_/Users/brehuang/dev/ember-cli-pemberly-i18n/node-tests/fixtures/ast-rewriter-test/sample1.gts/0_/Users/brehuang/dev/ember-cli-pemberly-i18n/node-tests/fixtures/ast-rewriter-test/sample1.gts/0_/Users/brehuang/dev/ember-cli-pemberly-i18n/node-tests/fixtures/ast-rewriter-test/sample1.gts:1
Rule: "prettier/prettier"
    at normalize (/Users/brehuang/dev/ember-cli-pemberly-i18n/node_modules/prettier/index.js:7737:19)
    at formatWithCursor2 (/Users/brehuang/dev/ember-cli-pemberly-i18n/node_modules/prettier/index.js:9006:50)
    at /Users/brehuang/dev/ember-cli-pemberly-i18n/node_modules/prettier/index.js:38183:12
    at Object.format (/Users/brehuang/dev/ember-cli-pemberly-i18n/node_modules/prettier/index.js:38197:12)
    at Program (/Users/brehuang/dev/ember-cli-pemberly-i18n/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js:266:41)
    at ruleErrorHandler (/Users/brehuang/dev/rehearsal-js-1/node_modules/.pnpm/eslint@8.34.0/node_modules/eslint/lib/linter/linter.js:1118:28)
    at /Users/brehuang/dev/rehearsal-js-1/node_modules/.pnpm/eslint@8.34.0/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/brehuang/dev/rehearsal-js-1/node_modules/.pnpm/eslint@8.34.0/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/brehuang/dev/rehearsal-js-1/node_modules/.pnpm/eslint@8.34.0/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
```

Content of the file involved:
```
import Component from "@glimmer/component";

export default class I18nTest extends Component {
  <template>
    {{!test-i18n-resource}}
    {{#if "true"}}
      <h1>This is untranslated text!</h1>
    {{/if}}
  </template>
}
```

**Comment by lynchbomb** [comment]
This should be fixed in internal config. IIRC the repo you’ve migrated is missing a dep. @cafreeman confirm
