### ISSUE TITLE
Bug: migrate errs out if .rehearsal is in .gitignore

### ISSUE THREAD

**Issue by brendaHuang-2023** [rehearsal-js/rehearsal-js#950]
Having .rehearsal in .gitignore should not be a blocker for running `migrate`.

```
error:   .rehearsal directory is ignored by .gitignore file. Please remove it from .gitignore file and try again.
Error: .rehearsal directory is ignored by .gitignore file. Please remove it from .gitignore file and try again.
    at checkGitIgnore (file:///Users/brehuang/dev/rehearsal-js/packages/cli/dist/src/commands/migrate/tasks/validate.js:35:15)
    at Task.task (file:///Users/brehuang/dev/rehearsal-js/packages/cli/dist/src/commands/migrate/tasks/validate.js:51:13)
    at Task.run (file:///Users/brehuang/dev/rehearsal-js/node_modules/.pnpm/listr2@5.0.7_enquirer@2.3.6/node_modules/listr2/dist/index.js:935:35)
```

**Comment by lynchbomb** [comment]
Rehearsal relies on .rehearsal directory for state management and reporting. Functionally this directory should be checked in. This check validates the directory can be checked in. (Feature)
